### ISSUE TITLE
deployment for machine learning model

### ISSUE THREAD

**Issue by helloavani** [douglas125/AzureMLDeploy#1]
i am currently working on machine learninig diabetes prediction model . i have finalized the model but now next difficult part is how to deploy this into real world via web application.

**Comment by douglas125** [comment]
One way would be to leave a server running as described in https://towardsdatascience.com/a-simple-way-to-deploy-any-machine-learning-model-106d463e9a4b

Or you could run the python app directly in the docker, your choice.

**Comment by raviyadav44** [comment]
What I suggest is if you know flask you can make a web app and then deploy it to some platforms like Heroku n all but what I use to do is for frontend I use streamlit it. you can refer to this amazing blog https://ljvmiranda921.github.io/notebook/2020/11/15/data-science-swe/

**Comment by douglas125** [comment]
I agree - nowadays you could use Sagemaker model serving as well. It's not as quick-and-dirty though.
https://docs.aws.amazon.com/sagemaker/latest/dg/how-it-works-deployment.html
