### ISSUE TITLE
Is the model being loaded again and again for every prediction?

### ISSUE THREAD

**Issue by rishabhsahrawat** [douglas125/AzureMLDeploy#2]
Hi, as the title says. That is my question. If yes, then doesn't that a lot of time in loading before predicting the image?. If not/yes, is there a way to load the model only once and then use the same instance for every user input image?

Thanks!

**Comment by douglas125** [comment]
I think this is somewhat late but I'll answer anyways.

No, the model does not need to be reloaded every time - it just needs to be loaded before pulling data for inference and sending results back.
